// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhonesMvc.Models;

namespace PhonesMvc.Migrations
{
    [DbContext(typeof(PhonesMvcContext))]
    partial class PhonesMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhonesMvc.Models.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("Owner");

                    b.Property<string>("PhoneNumber");

                    b.Property<float>("ScreenSize");

                    b.Property<string>("Sim");

                    b.HasKey("ID");

                    b.ToTable("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
